"""Beginner plotting helpers for the Week 2 time-series on-ramp."""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg", force=False)
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from fintools.figures import (
    FigureContext,
    add_source_note,
    export_figure_bundle,
    save_figure,
    time_series_plot,
    validate_axes_labels,
    validate_figure_context,
    validate_horizontal_grid,
    validate_image_not_blank,
)

DEFAULT_DATA_PATH = Path("fins2026/week2/results/data/week2_beginner_synthetic_prices.csv")
DEFAULT_OUTPUT_DIR = Path("fins2026/week2/results/figures/beginner_plotting")
DEFAULT_TICKER = "SYNTH"
DEFAULT_START_DATE = "2025-01-02"
DEFAULT_PERIODS = 50
DEFAULT_START_PRICE = 100.0
DEFAULT_RANDOM_SEED = 2026


def find_repo_root(start: Path | None = None) -> Path:
    """Find the repo root from a file or directory inside the repo."""

    current = (start or Path(__file__)).resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "pyproject.toml").is_file() and (
            candidate / "tools" / "workflow_lib.py"
        ).is_file():
            return candidate
    raise RuntimeError("Could not find the fins-agent repo root.")


def resolve_repo_path(path: str | Path, repo_root: Path | None = None) -> Path:
    """Resolve a repo-relative or absolute path."""

    resolved = Path(path)
    if resolved.is_absolute():
        return resolved
    return (repo_root or find_repo_root()).resolve() / resolved


def make_synthetic_price_frame(
    *,
    start: str = DEFAULT_START_DATE,
    periods: int = DEFAULT_PERIODS,
    ticker: str = DEFAULT_TICKER,
    start_price: float = DEFAULT_START_PRICE,
    seed: int = DEFAULT_RANDOM_SEED,
) -> pd.DataFrame:
    """Return one deterministic synthetic daily price series on business days."""

    if periods < 2:
        raise ValueError("periods must be at least 2")
    if start_price <= 0:
        raise ValueError("start_price must be positive")

    dates = pd.bdate_range(start=start, periods=periods)
    rng = np.random.default_rng(seed)
    daily_moves = np.r_[0.0, rng.normal(loc=0.45, scale=0.85, size=periods - 1)]
    prices = start_price + np.cumsum(daily_moves)
    if float(prices.min()) <= 0:
        raise RuntimeError("synthetic prices must stay positive")

    return pd.DataFrame(
        {
            "date": dates,
            "ticker": ticker,
            "price": np.round(prices, 2),
        }
    )


def write_synthetic_prices_csv(
    path: str | Path = DEFAULT_DATA_PATH,
    *,
    repo_root: Path | None = None,
) -> tuple[Path, pd.DataFrame]:
    """Write the canonical beginner synthetic price CSV and return it."""

    frame = make_synthetic_price_frame()
    output_path = resolve_repo_path(path, repo_root)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    export_frame = frame.assign(date=frame["date"].dt.strftime("%Y-%m-%d"))
    export_frame.to_csv(output_path, index=False)
    return output_path, frame


def load_synthetic_prices(
    path: str | Path = DEFAULT_DATA_PATH,
    *,
    repo_root: Path | None = None,
) -> pd.DataFrame:
    """Load the beginner synthetic price CSV."""

    data_path = resolve_repo_path(path, repo_root)
    frame = pd.read_csv(data_path, parse_dates=["date"])
    return frame.sort_values("date").reset_index(drop=True)


def beginner_sample_label(frame: pd.DataFrame) -> str:
    """Return a compact sample-period label for the synthetic frame."""

    ordered = frame.sort_values("date")
    start = pd.to_datetime(ordered["date"]).min()
    end = pd.to_datetime(ordered["date"]).max()
    return f"{start:%Y-%m-%d} to {end:%Y-%m-%d}"


def beginner_figure_context(frame: pd.DataFrame) -> FigureContext:
    """Return the caption sidecar used for the FT-style beginner figure."""

    return FigureContext(
        title="Synthetic Price Series",
        note=(
            "Week 2 beginner plotting on-ramp. Students first build the same one-series "
            "story with plain Matplotlib, then rebuild it with the Week 2 FT-style helper."
        ),
        source=(
            "Synthetic data generated by "
            "fins2026/week2/scripts/make_beginner_synthetic_prices.py."
        ),
        sample=beginner_sample_label(frame),
        units="Price level in dollars",
    )


def build_simple_time_series_figure(frame: pd.DataFrame) -> tuple[plt.Figure, plt.Axes]:
    """Build the plain Matplotlib beginner line chart."""

    ordered = frame.sort_values("date").reset_index(drop=True)
    fig, ax = plt.subplots(figsize=(7.0, 4.0))
    ax.plot(
        ordered["date"],
        ordered["price"],
        color="#1F77B4",
        linewidth=2.0,
    )
    ax.set_title("Synthetic Price Series", loc="left", fontweight="bold")
    ax.set_xlabel("Date")
    ax.set_ylabel("Price ($)")
    ax.grid(True, axis="y", alpha=0.35)
    ax.grid(False, axis="x")

    locator = mdates.AutoDateLocator(minticks=4, maxticks=6)
    formatter = mdates.ConciseDateFormatter(locator)
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(formatter)
    fig.autofmt_xdate(rotation=0, ha="center")
    fig.tight_layout(rect=(0.0, 0.05, 1.0, 1.0))
    fig.text(
        0.01,
        0.01,
        f"Synthetic data. Sample: {beginner_sample_label(ordered)}.",
        ha="left",
        va="bottom",
        fontsize=9.0,
        color="#4A5568",
    )
    return fig, ax


def build_ft_time_series_figure(frame: pd.DataFrame) -> tuple[plt.Figure, plt.Axes]:
    """Build the FT-style version of the beginner line chart."""

    ordered = frame.sort_values("date").reset_index(drop=True)
    fig, ax = time_series_plot(
        ordered,
        "price",
        date="date",
        title="Synthetic Price Series",
        ylabel="Price ($)",
        xlabel="Date",
        shade_recessions=False,
        legend=False,
        profile="word_a4",
        style="ft",
        direct_labels=False,
        line_width=1.8,
        line_alpha=0.95,
    )
    add_source_note(
        fig,
        (
            "Synthetic data | "
            f"Sample: {beginner_sample_label(ordered)} | Units: Price ($)"
        ),
        style="ft",
    )
    return fig, ax


def export_simple_time_series(
    frame: pd.DataFrame,
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    *,
    repo_root: Path | None = None,
) -> dict[str, Path]:
    """Export the plain Matplotlib beginner chart."""

    fig, ax = build_simple_time_series_figure(frame)
    issues = [
        *validate_axes_labels(ax),
        *validate_horizontal_grid(ax),
    ]
    if issues:
        details = "; ".join(issue.message for issue in issues)
        plt.close(fig)
        raise RuntimeError(f"simple beginner figure failed validation: {details}")

    output_root = resolve_repo_path(output_dir, repo_root)
    output_root.mkdir(parents=True, exist_ok=True)
    paths = {
        "png": save_figure(
            fig,
            output_root / "week2_beginner_simple_time_series.png",
        ),
        "pdf": save_figure(
            fig,
            output_root / "week2_beginner_simple_time_series.pdf",
        ),
    }
    image_issues = validate_image_not_blank(paths["png"])
    if image_issues:
        details = "; ".join(issue.message for issue in image_issues)
        plt.close(fig)
        raise RuntimeError(f"simple beginner figure failed image validation: {details}")
    plt.close(fig)
    return paths


def export_ft_time_series(
    frame: pd.DataFrame,
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    *,
    repo_root: Path | None = None,
) -> dict[str, Path]:
    """Export the FT-style beginner chart plus caption sidecar."""

    context = beginner_figure_context(frame)
    context_issues = validate_figure_context(context)
    if context_issues:
        details = "; ".join(issue.message for issue in context_issues)
        raise RuntimeError(f"FT beginner context failed validation: {details}")

    fig, ax = build_ft_time_series_figure(frame)
    axis_issues = [
        *validate_axes_labels(ax),
        *validate_horizontal_grid(ax),
    ]
    if axis_issues:
        details = "; ".join(issue.message for issue in axis_issues)
        plt.close(fig)
        raise RuntimeError(f"FT beginner figure failed validation: {details}")

    output_root = resolve_repo_path(output_dir, repo_root)
    paths = export_figure_bundle(
        fig,
        output_root,
        "week2_beginner_ft_time_series",
        context=context,
    )
    image_issues = validate_image_not_blank(paths["png"])
    if image_issues:
        details = "; ".join(issue.message for issue in image_issues)
        plt.close(fig)
        raise RuntimeError(f"FT beginner figure failed image validation: {details}")
    plt.close(fig)
    return paths
